services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: urlshortener-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: UrlShortener.API/Dockerfile
    container_name: urlshortener-api
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=UrlShortenerDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Encrypt=False"
    ports:
      - "8080:8080"

  web:
    build:
      context: ./urlshortener-web
      dockerfile: Dockerfile
    container_name: urlshortener-web
    depends_on:
      - api
    ports:
      - "3000:80"

volumes:
  sqlserver_data: